### ISSUE TITLE
Delete main and redo it

### ISSUE THREAD

**Issue by Maronato** [ProjetoALES/AlesWebsite2019#11]
[main](https://github.com/ProjetoALES/AlesWebsite2019/tree/master/main), especially [models.py](https://github.com/ProjetoALES/AlesWebsite2019/blob/master/main/models.py) is all over the place. It does not follow any style guidelines and does not follow our agreement of separating models and functions into specialized apps.

Delete and redo.

**Comment by gnsoares** [comment]
see #16
