### ISSUE TITLE
Padrão de código 

### ISSUE THREAD

**Issue by Maronato** [ProjetoALES/AlesWebsite2019#6]
Vi que vocês tão submetendo vários, PRs, o que é muito bom, mas o padrão de código tá bem oscilante. O Soares parece estar seguindo o PEP8, mas o Chris não.

Vamos definir aqui que os pull requests só vão poder ser aceitos se pelo menos uma outra pessoa aprovar. Para aprovar, tem que:

- Estar tudo compatível com o PEP8
- Estar tudo documentado 
- Se conter módulos lógicos, ter unit tests 

Todo mundo de acordo?

**Comment by Maronato** [comment]
Em particular, sobre o PEP8, se vocês estiverem tendo dificuldades pra manter o padrão manualmente, recomendo instalarem um linter no editor de vocês.
Se quiserem ascender em sua qualidade e entrega de código, recomendo usarem o Sublime Text 3 como editor e usar o [Anaconda] (http://damnwidget.github.io/anaconda/). Ele faz tudo que vocês podem imaginar, desde apontar todos os erros no seu código, inclusive os de PEP8, até abrir o source code de qualquer classe ou função de Python e django só clicando em cima da chamada. Assim vcs podem entender como a função ou classe funciona e alterá-la fazendo uma subclasse (se acostumem com a ideia de criar subclasses das classes padrões de django, pq vamos fazer isso direto pra conseguir os comportamentos que precisamos)

**Comment by ChrisKonishi** [comment]
Eu acho válido, vou me adequar pra a isso

**Comment by gnsoares** [comment]
Ok
