### ISSUE TITLE
Separação lógica por apps

### ISSUE THREAD

**Issue by Maronato** [ProjetoALES/AlesWebsite2019#7]
É extremamente importante separar a lógica do site em vários apps diferentes.

Atualmente vocês tão colocando tudo em `main` e isso é uma **péssima** prática.

O master já tem umas modificações que estão nessa vibe, então algum de vocês, crie um pull request colocando os modelos que tão lá em apps específicas e, nos outros PRs, coloquem sua lógica em apps específicos. 

Não tem que ser um App por modelo, mas é importante separar em blocos lógicos para que seja possível ler o código quando o site tiver 1000+ linhas.

Se todos os modelos ficarem num arquivo só, vai ser impossível de ler e manter o código

**Comment by vpalmerini** [comment]
“If you can’t explain what your app does in one sentence, it should be more than one app” - by someone

**Comment by gnsoares** [comment]
Entendi. Você tem alguma sugestão pra em quais apps separar?

**Comment by gnsoares** [comment]
see #16
